insert into actor (first_name, last_name, date_of_birth) values ('Brooks', 'Vickars', '21.08.2002');
insert into actor (first_name, last_name, date_of_birth) values ('Bev', 'Giordano', '16.03.1968');
insert into actor (first_name, last_name, date_of_birth) values ('Caritta', 'Bold', '09.03.1956');
insert into actor (first_name, last_name, date_of_birth) values ('Fielding', 'Winspare', '02.11.1968');
insert into actor (first_name, last_name, date_of_birth) values ('Sapphire', 'McLagain', '11.08.1964');
insert into actor (first_name, last_name, date_of_birth) values ('Eberhard', 'Jurczyk', '12.03.1963');
insert into actor (first_name, last_name, date_of_birth) values ('Alexandr', 'Margett', '23.03.1971');
insert into actor (first_name, last_name, date_of_birth) values ('Tucky', 'Kington', '05.09.1974');
insert into actor (first_name, last_name, date_of_birth) values ('Melli', 'Kenningley', '07.12.1953');
insert into actor (first_name, last_name, date_of_birth) values ('Bryana', 'Blasdale', '25.07.1953');
insert into actor (first_name, last_name, date_of_birth) values ('Bernete', 'Raye', '29.07.2002');
insert into actor (first_name, last_name, date_of_birth) values ('Huntley', 'Ambrozik', '22.10.2001');
insert into actor (first_name, last_name, date_of_birth) values ('Hersch', 'Kores', '27.05.1954');
insert into actor (first_name, last_name, date_of_birth) values ('Jocelyne', 'Gribble', '20.11.1956');
insert into actor (first_name, last_name, date_of_birth) values ('Stacee', 'Hedgeman', '24.01.1957');
insert into actor (first_name, last_name, date_of_birth) values ('Revkah', 'Halloran', '05.03.1983');
insert into actor (first_name, last_name, date_of_birth) values ('Adler', 'Goddman', '19.06.1980');
insert into actor (first_name, last_name, date_of_birth) values ('Hastings', 'Kidwell', '02.12.1970');
insert into actor (first_name, last_name, date_of_birth) values ('Sharia', 'Watts', '28.07.1989');
insert into actor (first_name, last_name, date_of_birth) values ('Nicko', 'Rennick', '08.12.1971');
insert into actor (first_name, last_name, date_of_birth) values ('Isaac', 'Swire', '28.04.1988');
insert into actor (first_name, last_name, date_of_birth) values ('Lurline', 'Samper', '26.02.1985');
insert into actor (first_name, last_name, date_of_birth) values ('Otis', 'Fontes', '20.02.1969');
insert into actor (first_name, last_name, date_of_birth) values ('Tye', 'Stelle', '15.02.1988');
insert into actor (first_name, last_name, date_of_birth) values ('Annadiane', 'Bettley', '16.08.1991');
insert into actor (first_name, last_name, date_of_birth) values ('Raynell', 'Gelling', '09.02.1963');
insert into actor (first_name, last_name, date_of_birth) values ('Petronille', 'Gormley', '03.12.1965');
insert into actor (first_name, last_name, date_of_birth) values ('Franni', 'Gehricke', '04.04.1978');
insert into actor (first_name, last_name, date_of_birth) values ('Karalee', 'Othen', '27.07.2001');
insert into actor (first_name, last_name, date_of_birth) values ('Phylys', 'Bernlin', '06.09.1982');
insert into actor (first_name, last_name, date_of_birth) values ('Lorrin', 'Benezet', '09.10.1979');
insert into actor (first_name, last_name, date_of_birth) values ('George', 'Klemt', '25.05.1963');
insert into actor (first_name, last_name, date_of_birth) values ('Cece', 'Woolacott', '18.03.1950');
insert into actor (first_name, last_name, date_of_birth) values ('Obie', 'Ranaghan', '23.05.1986');
insert into actor (first_name, last_name, date_of_birth) values ('Vittorio', 'Soot', '13.02.1955');
insert into actor (first_name, last_name, date_of_birth) values ('Charla', 'Burn', '27.12.1966');
insert into actor (first_name, last_name, date_of_birth) values ('Kali', 'Blincow', '31.01.1981');
insert into actor (first_name, last_name, date_of_birth) values ('Jenna', 'Clemetts', '10.10.1950');
insert into actor (first_name, last_name, date_of_birth) values ('Augie', 'Goodier', '14.04.1986');
insert into actor (first_name, last_name, date_of_birth) values ('Gerda', 'Carren', '20.09.1995');
insert into actor (first_name, last_name, date_of_birth) values ('Imelda', 'Hagyard', '05.02.1957');
insert into actor (first_name, last_name, date_of_birth) values ('Debi', 'Harflete', '16.06.1957');
insert into actor (first_name, last_name, date_of_birth) values ('Alma', 'Dalloway', '30.04.1952');
insert into actor (first_name, last_name, date_of_birth) values ('Bryce', 'Mecozzi', '26.11.1973');
insert into actor (first_name, last_name, date_of_birth) values ('Eberto', 'Clapperton', '03.06.1976');
insert into actor (first_name, last_name, date_of_birth) values ('Annabal', 'Kelsow', '30.06.1992');
insert into actor (first_name, last_name, date_of_birth) values ('Temp', 'Viveash', '31.07.1956');
insert into actor (first_name, last_name, date_of_birth) values ('Farrell', 'Rothermel', '18.09.1978');
insert into actor (first_name, last_name, date_of_birth) values ('Bailey', 'Filippov', '06.09.1980');
insert into actor (first_name, last_name, date_of_birth) values ('Odell', 'Lydiate', '03.04.1964');

insert into producer (first_name, last_name, date_of_birth, categorie) values ('Noel', 'Eyes', '10.12.1983', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Powell', 'Brommage', '18.04.1974', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Lauralee', 'De Beneditti', '04.04.1996', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Deidre', 'Snowden', '03.08.2001', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Lonna', 'Vagg', '19.10.1954', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Wilfrid', 'Seldner', '03.05.1995', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Matt', 'Pfeiffer', '28.12.1995', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Leona', 'Robbel', '28.09.1956', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Rab', 'Bertson', '18.06.1972', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Karyl', 'Dyball', '06.12.1987', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Rhianon', 'Milkin', '24.03.1998', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Moll', 'Teasdale-Markie', '07.10.1969', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Giorgio', 'Lisimore', '03.03.1967', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Olia', 'Cohn', '25.08.1958', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Linzy', 'Le Borgne', '24.08.1967', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Jared', 'Wetter', '22.09.1999', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Gradey', 'Gianolo', '02.05.1951', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Klement', 'Ilive', '11.01.1983', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Kip', 'Toombes', '26.12.1952', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Burnard', 'Warmisham', '02.11.1987', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Salaidh', 'Kleinmann', '13.10.1993', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Graham', 'Couve', '18.08.1966', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Willa', 'Lergan', '29.04.1988', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Cybil', 'Urvoy', '19.03.1953', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Kass', 'Wymer', '27.08.1977', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Blayne', 'Naris', '13.05.1996', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Ianthe', 'Ronchka', '06.10.1961', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Lind', 'Ettels', '01.01.1978', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Theresina', 'Dumphries', '14.11.1959', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Ninnette', 'Goodered', '15.05.1971', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Tadeo', 'Weetch', '19.05.1983', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Johnathan', 'Brevitt', '31.03.1962', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Lindi', 'Pavia', '07.06.1988', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Baudoin', 'Lamb', '02.07.1986', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Galina', 'Notton', '06.05.1966', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Sebastien', 'Kabos', '20.02.1980', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Conchita', 'Boggs', '06.07.1950', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Geordie', 'Lambertazzi', '26.01.1986', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Hamel', 'Crebbin', '30.10.2001', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Sherwynd', 'Caren', '13.09.1966', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Bruce', 'Alban', '27.06.1954', 'artist');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Frederich', 'Depka', '24.01.1952', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Petrina', 'Harry', '18.11.2002', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Jocelyne', 'Bradman', '09.09.1984', 'conductor');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Myles', 'Lubman', '05.09.1967', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Arvie', 'Langer', '30.09.1975', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Charlena', 'Alfonso', '09.02.1955', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Linc', 'Wallworth', '06.02.1979', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Linnet', 'Olivari', '16.04.2000', 'director');
insert into producer (first_name, last_name, date_of_birth, categorie) values ('Janene', 'McCoish', '09.11.1993', 'conductor');

insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Abram', 'Kubasiewicz', '22.06.1989', 6);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Penny', 'Kildale', '07.12.1976', 41);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Monroe', 'Bibb', '05.12.1984', 13);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Vale', 'Rivlin', '15.09.2002', 34);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Georgeta', 'Rouge', '09.09.1983', 41);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Virgilio', 'Olden', '04.11.2000', 37);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Shae', 'Pantecost', '09.05.1974', 30);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Lotty', 'Jikylls', '28.08.2000', 6);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Lena', 'Heinke', '17.12.1967', 38);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Alexi', 'Beaushaw', '24.02.1968', 18);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Cher', 'Skeech', '21.01.1970', 34);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Steffi', 'Duplain', '03.07.1999', 39);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Alic', 'Swayton', '17.09.1997', 7);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Em', 'Cowerd', '16.11.1964', 15);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Gualterio', 'Madelin', '10.01.1954', 20);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Dasha', 'Dalyiel', '30.11.1963', 26);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Cameron', 'Bowe', '24.01.2002', 48);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Ceciley', 'Slateford', '14.08.1993', 35);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Etta', 'Pflieger', '29.01.1951', 50);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Rockey', 'Brislane', '03.06.1975', 21);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Corrie', 'Windrass', '30.03.1966', 45);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Darcey', 'Crosham', '22.07.1989', 31);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Madelina', 'Fraczkiewicz', '22.07.1955', 6);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Georges', 'Howley', '26.06.1987', 47);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Angel', 'Sollom', '29.11.1960', 18);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Claudie', 'Underwood', '09.04.1991', 24);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Olly', 'Dunsmore', '22.01.1978', 22);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Ahmad', 'Besemer', '17.02.1984', 23);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Willetta', 'Bucknill', '20.06.1979', 38);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Janna', 'Chiverton', '07.05.1952', 17);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Dmitri', 'Lanegran', '15.03.1963', 30);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Zorina', 'Spens', '31.01.1999', 20);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Kaela', 'Trymme', '26.08.1958', 15);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Eleonore', 'Simms', '22.09.1973', 35);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Yard', 'Tunnock', '27.11.1951', 7);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Carolyn', 'Crier', '14.04.1994', 22);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Court', 'Betun', '05.06.1992', 1);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Abbi', 'Wiffield', '23.10.1994', 45);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Allene', 'Surgeon', '09.11.1958', 32);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Kearney', 'Bradder', '01.05.1992', 32);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Brnaba', 'Slavin', '31.10.2002', 41);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Udall', 'Ciabatteri', '12.03.1994', 4);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Amelia', 'Goadby', '14.09.1963', 48);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Clive', 'Kirkam', '05.05.1986', 37);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Nonna', 'Scruby', '24.10.1980', 2);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Tamqrah', 'Wraggs', '05.11.1974', 14);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Loydie', 'Breitling', '03.02.1960', 35);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Clay', 'Crowcum', '16.10.1989', 11);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Brande', 'Bayns', '28.05.2000', 28);
insert into understudy (first_name, last_name, date_of_birth, actor_id) values ('Cecile', 'Kinglesyd', '25.10.1991', 49);